apiVersion: apps/v1
kind: Deployment
metadata: 
    name: loiddep
    labels:
        app: hotels50k
spec:
    replicas: 1
    selector:
        matchLabels:
            app: hotels50k
    template:
        metadata:
            labels:
                app: hotels50k
        spec:
            volumes:
                - name: nfs-access
                  persistentVolumeClaim:
                    claimName: ogechivol1claim
            restartPolicy: Always
            nodeSelector:
                node-role.ida/gputitan: 'true'
            containers:
                - name: hotels50kcontainer
                  image: uloma07/hotels50k
                  ports:
                  - containerPort: 32000
                  volumeMounts:
                    - name: nfs-access
                      mountPath: /nfs/
                  resources:
                    limits:
                        cpu: '2000m'
                        memory: 4Gi
                        nvidia.com/gpu: '1'
                    requests:
                        cpu: '1000m'
                        memory: 1Gi
                        nvidia.com/gpu: '1'


