apiVersion: apps/v1
kind: Deployment
metadata: 
    name: loiddep
    namespace: ogechiproject
    labels:
        app: hotels50k
        group: ogechi
spec:
    replicas: 1
    selector:
        matchLabels:
            app: hotels50k
    template:
        metadata:
            labels:
                app: hotels50k
        spec:
            volumes:
                - name: nfs-access
                  persistentVolumeClaim:
                    claimName: ogechivol1claim
            restartPolicy: Always
            nodeSelector:
                node-role.ida/gputitan: 'true'
            containers:
                - name: hotels50kcontainer
                  image: uloma07/hotels50k
                  command: [ "/bin/bash", "-ec"]
                  args: [ date; sleep 10; echo 'Hello from the Kubernetes cluster'; sleep 1; while true; do sleep 20; done;]
                  ports:
                  - containerPort: 33000
                  volumeMounts:
                    - name: nfs-access
                      mountPath: /nfs
                      subPath: Hotels-50K
                  resources:
                    limits:
                        cpu: '2000m'
                        memory: 4Gi
                        nvidia.com/gpu: '1'
                    requests:
                        cpu: '1000m'
                        memory: 1Gi
                        nvidia.com/gpu: '1'


