apiVersion: v1
kind: Service
metadata:
  name: jupyterservice
  namespace: ogechiproject      
spec:
  selector:
    app: pytorchMLNotebook   
  ports:
  - name: jupyter
    port: 8888               
    protocol: TCP
    targetPort: 8888  
