apiVersion: apps/v1
kind: Deployment
metadata:
    name: pytorchmlnotebookgpu
    namespace: ogechiproject
    label:
        app: pytorchMLNotebook
        group: ogechi
spec:
    replicas: 1
    selector:
        matchLabels:
            app: pytorchMLNotebook
    template:
        metadata:
            labels:
                app: pytorchMLNotebook
                deployment: pythonMLNotebookGPU
                group: ogechi
        spec:
            nodeSelector:
                node-role.ida/gputitan: "true"
                # node-role.ida/gpu2080ti: "true"
            securityContext: {}
            serviceAccount: default
            containers:
                - name: pytorchmlcontainer
                  image: inferislux/zaiqiao-ml:latest
                  resources:
                    requests:
                        cpu: "2000m"
                        memory: "4Gi"
                        nvidia.com/gpu: 1
                    limits:
                        cpu: "2500m"
                        memory: "16Gi"
                        nvidia.com/gpu: 1
                  command:
                    - 'jupyter'
                  args:
                    - 'notebook'
                    - '--no-browser'
                    - '--ip=0.0.0.0'
                    - '--NotebookApp.token='
                  ports:
                    - containerPort: 8888
                  
                
                
